### ISSUE TITLE
confusion regarding auto id field

### ISSUE THREAD

**Issue by yyyyaaa** [constructive-io/launchql-v1#23]
when I create field id with type UUID, it will have defaultValue to "uuid_generate_v4()", what should I provide to the input of ```create<singular_table_name>``` mutation?

These input don't work:
- empty string
- null
- "uuid_generate_v4()"

error for option 1:
Expected type UUID, found \"\"; Invalid UUID, expected 32 hexadecimal characters, optionally with hypens

error for option 2:
null value in column \"id\" violates not-null constraint

error for option 3: same as option 1

**Comment by yyyyaaa** [comment]
if it is a caveat of postgraphile, should I generate the id on frontend side?

**Comment by pyramation** [comment]
Sorry I should have mentioned it before, you use `uuid_generate_v4()` -- no quotes!

Basically default value is the actual SQL value, so we pass it as a JS string, but that string is like real sql. So possible values, written in (pseudo) JavaScript for clarity:

```js
createFieldQuery ({
  table_id,
  name: 'id',
  type: 'uuid',
  default_value: 'uuid_generate_v4()'
});
```

For example, notice the string for `true`:

```js
createFieldQuery ({
  table_id,
  name: 'active',
  type: 'boolean',
  default_value: 'true'
});
```
