### ISSUE TITLE
many2many needs to be omitted

### ISSUE THREAD

**Issue by pyramation** [constructive-io/launchql-v1#27]
https://www.graphile.org/postgraphile/plugin-gallery/#Customisation__OmitMutationsByDefaultPlugin

potentially fork and omit by default, and only whitelist

**Comment by yyyyaaa** [comment]
Oh hey @pyramation will this be a breaking change?

**Comment by pyramation** [comment]
nope! Only if we had build an app that used some of relations not exposed. 

I had one breaking change for dbe, but updated their mobile dev and he fixed it.

![Screen Shot 2020-11-08 at 6 57 53 AM](https://user-images.githubusercontent.com/545047/98861219-27ca7600-2422-11eb-87fa-fdbddfe92fbc.png)

So as you can see here, I changed one of the crazy long names to a simple name, and omitted the rest. 

It's mostly and issue for the end users' api
